#Give tributes to "player" or to "chest". tribute chests must be a single chest block on top of a gold block. 
tributeMode: player

#The radius (in blocks) around the player or chest to get villager tributes from. 
tributeRange: 64

#The number of villagers per tribute
villagerCount: 20

#The minimum tribute size per X villagers
minPerVillagerCount: 0

#The maximum tribute size per X villagers
maxPerVillagerCount: 3

#Bonus tribute per X villagers if there was a zombie siege in the vicinity
baseSiegeBonus: 1

#The minimum tribute granted for killing a zombie siege mob.
minPerSiegeKill: 1

#The maximum tribute granted for killing a zombie siege mob.
maxPerSiegeKill: 2

#Radius around the initial siege location to spawn mobs in.
randomSpread: 16
randomVerticalSpread: 6

#Settings for each mob type. Settings are as follows:
#   threshold - minimum number of villagers required for this type of mob to spawn.
#   chance - % chance of this mob spawning if the threshold is met. ### SET TO 0 TO DISABLE THIS MOB. ###
#   max - max number of this mob that can spawn in a siege.
#   points - the number of popularity points killing this mob type will grant.
mobs:
  zombie:
    threshold: 1
    chance: 100
    points: 1
    max: 100
  skeleton:
    threshold: 20
    chance: 100
    points: 1
    max: 100
  spider:
    threshold: 20
    chance: 100
    points: 1
    max: 100
  cave_spider:
    threshold: 40
    chance: 100
    points: 10
    max: 100
  pig_zombie:
    threshold: 1
    chance: 0
    points: 1
    max: 100
  blaze:
    threshold: 40
    chance: 100
    points: 1
    max: 100
  witch:
    threshold: 40
    chance: 100
    points: 1
    max: 100
  magma_cube:
    threshold: 60
    chance: 0
    points: 1
    max: 10
  wither_skeleton:
    threshold: 60
    chance: 60
    points: 10
    max: 100
  enderman:
    threshold: 60
    chance: 0
    points: 1
    max: 100
  ghast:
    threshold: 80
    chance: 0
    points: 1
    max: 100
  wither:
    threshold: 150
    chance: 0
    points: 1
    max: 100
  ender_dragon:
    threshold: 150
    chance: 0
    points: 1
    max: 3