#Give tributes to "player" or to "chest". tribute chests must be a single chest block on top of a gold block. 
tributeMode: player

#The radius (in blocks) around the player or chest to get villager tributes from. 
tributeRange: 64

#The number of villagers per tribute
villagerCount: 20

#The minimum tribute size per X villagers
minPerVillagerCount: 0

#The maximum tribute size per X villagers
maxPerVillagerCount: 3

#Bonus tribute per X villagers if there was a zombie siege in the vicinity
baseSiegeBonus: 1

#The minimum tribute granted for killing a zombie siege mob.
minPerSiegeKill: 1

#The maximum tribute granted for killing a zombie siege mob.
maxPerSiegeKill: 2


ranks:
  hated:
    threshold: -1000
    multiplier: 0.0
  hostile:
    threshold: -100
    multiplier: 0.0
  unfriendly:
    threshold: -10
    multiplier: 0.0
  neutral:
    threshold: 0
    multiplier: 0.25
  friendly:
    threshold: 10
    multiplier: 0.5
  honored:
    threshold: 10
    multiplier: 0.75
  revered:
    threshold: 10
    multiplier: 1.0
  exalted:
    threshold: 10
    multiplier: 2.0

#Settings for each mob type. Settings are as follows:
#   threshold - minimum number of villagers required for this type of mob to spawn.
#   chance - % chance of this mob spawning if the threshold is met. ### SET TO 0 TO DISABLE THIS MOB. ###
#   max - max number of this mob that can spawn in a siege.
#   points - the number of popularity points killing this mob type will grant.
#Radius around the initial siege location to spawn mobs in.
siege:
  randomSpread: 16
  randomVerticalSpread: 6
  mobs:
    zombie:
      threshold: 1
      chance: 80
      points: 1
      max: 100
    skeleton:
      threshold: 20
      chance: 40
      points: 1
      max: 20
    spider:
      threshold: 20
      chance: 40
      points: 1
      max: 20
    cave_spider:
      threshold: 40
      chance: 40
      points: 10
      max: 20
    pig_zombie:
      threshold: 1
      chance: 0
      points: 1
      max: 20
    blaze:
      threshold: 40
      chance: 100
      points: 1
      max: 10
    witch:
      threshold: 40
      chance: 40
      points: 1
      max: 10
    magma_cube:
      threshold: 60
      chance: 0
      points: 1
      max: 10
    wither_skeleton:
      threshold: 60
      chance: 40
      points: 10
      max: 100
    enderman:
      threshold: 60
      chance: 0
      points: 1
      max: 100
    ghast:
      threshold: 80
      chance: 0
      points: 1
      max: 100
    wither:
      threshold: 150
      chance: 0
      points: 1
      max: 100
    ender_dragon:
      threshold: 150
      chance: 0
      points: 1
      max: 3

villages: {}