name: UVVillagers
main: net.uvnode.uvvillagers.UVVillagers
version: 0.0.6

commands:
   siege:
      description: This outputs information about a siege
      usage: /siege
      permission: uvvillagers.siege
      permission-message: You don't have <permission>