name: UVVillagers
main: net.uvnode.uvvillagers.UVVillagers
version: 0.2.2

commands:
   uvv:
      description: UVVillagers commands. Get nearest village info.
      usage: /uvv
      permission: uvvillagers.main
      permission-message: You don't have <permission>