name: UVVillagers
main: net.uvnode.uvvillagers.UVVillagers
version: 0.0.7

commands:
   uvv:
      description: UVVillagers commands. Get siege information or reload config.
      usage: /uvv [siege|reload]
      permission: uvvillagers.siege
      permission-message: You don't have <permission>